/**
 * Deployed contract addresses.
 *
 * Generated by scripts/write-addresses.ts from broadcast/DeployTestnet.s.sol/46630.
 * `usdg` is the vault `asset()` / `USDG_ADDRESS` (not deployed by this repo).
 * Mainnet stays null. Do not hand-edit invented addresses.
 */
import { CHAIN } from "@seat/sdk";

export interface AddressEntry {
  readonly riskModule: `0x${string}` | null;
  readonly swapAdapter: `0x${string}` | null;
  readonly feeModule: `0x${string}` | null;
  readonly deskFactory: `0x${string}` | null;
  readonly deskVault: `0x${string}` | null;
  readonly usdg: `0x${string}` | null;
}

export const EMPTY: AddressEntry = {
  riskModule: null,
  swapAdapter: null,
  feeModule: null,
  deskFactory: null,
  deskVault: null,
  usdg: null,
};

const TESTNET: AddressEntry = {
  riskModule: "0x48a0733a5b7b7ae1c98d29712cc639f33bcb2147",
  swapAdapter: "0xff8851ea3699781c6c331ee9530d7831cc465f02",
  feeModule: "0x475d9d5a7d1b839845ee1073c5a0c51320064408",
  deskFactory: "0x4c58691ad3395d9a9fa078b2d86a1c5d90a73e10",
  deskVault: "0x8ff6ef04312679a0112b5229c6911cbc026e73ff",
  usdg: "0x7e955252e15c84f5768b83c41a71f9eba181802f",
};

/** Addresses keyed by chain id. 46630 is filled from deploy logs, never invented. */
export const ADDRESSES: Record<number, AddressEntry> = {
  [CHAIN.MAINNET_ID]: EMPTY,
  [CHAIN.TESTNET_ID]: TESTNET,
};

export function getAddresses(chainId: number): AddressEntry {
  return ADDRESSES[chainId] ?? EMPTY;
}

export function hasTestnetVault(entry: AddressEntry): boolean {
  return entry.deskVault !== null;
}

/** Writes are allowed only on Robinhood testnet with a real vault address. */
export function canWriteOnChain(chainId: number, entry: AddressEntry): boolean {
  if (chainId === CHAIN.MAINNET_ID) return false;
  if (chainId !== CHAIN.TESTNET_ID) return false;
  return entry.deskVault !== null;
}
