/**
 * Write app/src/lib/addresses.ts 46630 entries from a Foundry broadcast.
 *
 * Reads broadcast/DeployTestnet.s.sol/46630/run-latest.json when present.
 * Does not invent addresses. Mainnet stays null. If no broadcast file
 * exists, the file is left as the empty (null) map.
 *
 * Optional USDG_ADDRESS env is recorded when set (USDG is not deployed here).
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BROADCAST = join(
  ROOT,
  "broadcast",
  "DeployTestnet.s.sol",
  "46630",
  "run-latest.json",
);
const OUT = join(ROOT, "app", "src", "lib", "addresses.ts");

interface BroadcastTx {
  contractName?: string;
  contractAddress?: string;
  transactionType?: string;
}

interface BroadcastFile {
  transactions?: BroadcastTx[];
}

function asAddr(value: string | undefined): `0x${string}` | null {
  if (!value) return null;
  const v = value.trim();
  if (!/^0x[0-9a-fA-F]{40}$/.test(v)) return null;
  return v.toLowerCase() as `0x${string}`;
}

function findAddr(txs: BroadcastTx[], name: string): `0x${string}` | null {
  for (const tx of txs) {
    if (tx.contractName === name && tx.contractAddress) {
      return asAddr(tx.contractAddress);
    }
  }
  return null;
}

function main(): void {
  if (!existsSync(BROADCAST)) {
    console.log(
      `[write-addresses] no broadcast at ${BROADCAST}; leaving 46630 addresses null`,
    );
    return;
  }

  const raw = JSON.parse(readFileSync(BROADCAST, "utf8")) as BroadcastFile;
  const txs = raw.transactions ?? [];

  const usdgEnv = asAddr(process.env.USDG_ADDRESS);
  const entry = {
    riskModule: findAddr(txs, "RiskModule"),
    swapAdapter: findAddr(txs, "SwapAdapter"),
    feeModule: findAddr(txs, "FeeModule"),
    deskFactory: findAddr(txs, "DeskFactory"),
    deskVault: findAddr(txs, "DeskVault"),
    usdg: usdgEnv,
  };

  const body = `/**
 * Deployed contract addresses.
 *
 * Generated by scripts/write-addresses.ts from broadcast/DeployTestnet.s.sol/46630.
 * \`usdg\` is the vault \`asset()\` / \`USDG_ADDRESS\` (not deployed by this repo).
 * Mainnet stays null. Do not hand-edit invented addresses.
 */
import { CHAIN } from "@seat/sdk";

export interface AddressEntry {
  readonly riskModule: \`0x\${string}\` | null;
  readonly swapAdapter: \`0x\${string}\` | null;
  readonly feeModule: \`0x\${string}\` | null;
  readonly deskFactory: \`0x\${string}\` | null;
  readonly deskVault: \`0x\${string}\` | null;
  readonly usdg: \`0x\${string}\` | null;
}

export const EMPTY: AddressEntry = {
  riskModule: null,
  swapAdapter: null,
  feeModule: null,
  deskFactory: null,
  deskVault: null,
  usdg: null,
};

const TESTNET: AddressEntry = {
  riskModule: ${jsonAddr(entry.riskModule)},
  swapAdapter: ${jsonAddr(entry.swapAdapter)},
  feeModule: ${jsonAddr(entry.feeModule)},
  deskFactory: ${jsonAddr(entry.deskFactory)},
  deskVault: ${jsonAddr(entry.deskVault)},
  usdg: ${jsonAddr(entry.usdg)},
};

/** Addresses keyed by chain id. 46630 is filled from deploy logs, never invented. */
export const ADDRESSES: Record<number, AddressEntry> = {
  [CHAIN.MAINNET_ID]: EMPTY,
  [CHAIN.TESTNET_ID]: TESTNET,
};

export function getAddresses(chainId: number): AddressEntry {
  return ADDRESSES[chainId] ?? EMPTY;
}

export function hasTestnetVault(entry: AddressEntry): boolean {
  return entry.deskVault !== null;
}

/** Writes are allowed only on Robinhood testnet with a real vault address. */
export function canWriteOnChain(chainId: number, entry: AddressEntry): boolean {
  if (chainId === CHAIN.MAINNET_ID) return false;
  if (chainId !== CHAIN.TESTNET_ID) return false;
  return entry.deskVault !== null;
}
`;

  writeFileSync(OUT, body);
  console.log("[write-addresses] wrote 46630 addresses:", entry);
}

function jsonAddr(addr: `0x${string}` | null): string {
  return addr ? `"${addr}"` : "null";
}

main();
